// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    [Migration("20210711055434_Initia")]
    partial class Initia
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkLocation")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkLocation = "Washington",
                            ParkName = "Mount Rainier"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkLocation = "Washington",
                            ParkName = "North Cascades"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkLocation = "Utah",
                            ParkName = "Zion"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkLocation = "Virginia",
                            ParkName = "Shenandoah"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkLocation = "California",
                            ParkName = "Redwood"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
