// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ParksLookup.Models;

namespace ParksLookup.Migrations
{
    [DbContext(typeof(ParksLookupContext))]
    partial class ParksLookupContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("ParksLookup.Models.Park", b =>
                {
                    b.Property<int>("ParkId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ParkLocation")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ParkName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("ParkId");

                    b.ToTable("Parks");

                    b.HasData(
                        new
                        {
                            ParkId = 1,
                            ParkLocation = "Wyoming",
                            ParkName = "Yellowstone National Park"
                        },
                        new
                        {
                            ParkId = 2,
                            ParkLocation = "Montana",
                            ParkName = "Glacier National Park"
                        },
                        new
                        {
                            ParkId = 3,
                            ParkLocation = "Arzona",
                            ParkName = "Grand Canyon National Park"
                        },
                        new
                        {
                            ParkId = 4,
                            ParkLocation = "Oregon",
                            ParkName = "Crater Lake National Park"
                        },
                        new
                        {
                            ParkId = 5,
                            ParkLocation = "California",
                            ParkName = "Joshua Tree National Park"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
